const js = require("@eslint/js");

module.exports = [
  js.configs.recommended,
  {
    languageOptions: {
      globals: {
        document: "readonly",
        window: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        fetch: "readonly",
        Request: "readonly",
        Response: "readonly",
        Headers: "readonly",
        Notification: "readonly",
        Image: "readonly",
        Audio: "readonly",
        Blob: "readonly",
        File: "readonly",
        FileReader: "readonly",
        FormData: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        crypto: "readonly",
        performance: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        IntersectionObserver: "readonly",
        MutationObserver: "readonly",
        ResizeObserver: "readonly",
        RTCPeerConnection: "readonly",
        RTCSessionDescription: "readonly",
        RTCIceCandidate: "readonly",
        MediaStream: "readonly",
        MediaRecorder: "readonly",
        Atomics: "readonly",
        SharedArrayBuffer: "readonly",
        firebase: "readonly",
      },
      ecmaVersion: "latest",
      sourceType: "script",
    },
    rules: {
      "no-unused-vars": ["warn", { args: "none", varsIgnorePattern: "^_" }],
      "no-var": "off",
      "prefer-const": "warn",
      "no-undef": "off",
      "eqeqeq": "warn",
      "no-console": "off",
      "no-restricted-globals": "off",
      "no-func-assign": "off",
      "no-empty": "warn",
    },
  },
];
